### ISSUE TITLE
Draw Alanı Araştırması

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/Icon-Projesi#11]

**Comment by serdariset** [comment]
![Frame 15](https://user-images.githubusercontent.com/73692800/146980087-767c5697-30bd-47d5-b696-9fbde09725a5.jpg)
![image 2](https://user-images.githubusercontent.com/73692800/146980095-c5e88726-4efe-461f-ace0-0f075e90abd6.png)
![image 3](https://user-images.githubusercontent.com/73692800/146980099-033716e0-d8e3-4ccd-85e9-1f7f71fcda75.png)
