### ISSUE TITLE
Tasarım: Layout ve Renkler, CSS kontrolü

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/Icon-Projesi#23]
**Türü:** Tasarım, Kodlama
**Tanım:** Layout, renklerin ve css arayüzün kontrol edilmesi
**Beklenen Çıktı:** Code Commitleri

**Comment by sinanaksu** [comment]
Çalışmalarda Kullanılan ve init projeye alınan CSS'ler
Ata Türkoğlu -> Bootstrap
Cumali Tezcan -> Bootstrap + drobzone
Eralp Özcan -> Google Font + FontAwesome
