### ISSUE TITLE
Özellik: .zip Çıktısı alma

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/Icon-Projesi#31]
**Türü:** Araştırma, Kodlama
**Tanım:** .zip olarak çıktı nasıl alınabilir araştırma, belki  küçük bir demo
**Ortam:** Electron.js, Diğer
**Beklenen Çıktı:** Rapor veya Demo

**Comment by ata-turkoglu** [comment]
basit halini yükledim, geliştirilecek
