### ISSUE TITLE
Araştırma: User İşlemleri ve Olası Features

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/Icon-Projesi#33]
**Türü:** Araştırma
**Tanım:**  User işlemleri ekranı için olası ne tür özellik eklenebilir, araştır
**Beklenen Çıktı:** Rapor veya Örnek Kod

**Comment by Eralpozcan** [comment]
-  Şifre değiştirme
-  Email değiştirme
-  İsim-Soyad Kullanılacaksa değiştirme özelliği
-  Avatar kullanılacaksa avatar değiştirme özelliği
-  Finansal gelir modeli elde edecekse banka hesabı bilgileri değiştirme özelliği
-  Ülke değiştirme (Trendler için)
-  Üyelik silme
-  Ücretli Üyelik İptali 
-  Darkmod Özelliği
-  Font Değiştirme Özelliği İşlemi
-  Dil Seçeneği
