### ISSUE TITLE
Özellik: .PNG Dosyasını .ICO Convert Etme

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/Icon-Projesi#36]
**Türü:** Coding
**Tanım:** .PNG dosyalarının .ico dosyasına convert edilmesinin araştırılması ve bir örnek program yazılması
**Ortam:** Electron.js, diğer diller
**Beklenen Çıktı:** Kod Örneği

**Comment by cumalitezcan** [comment]
close issue
