### ISSUE TITLE
Araştırma: User İşlemleri Olası Features

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/Icon-Projesi#46]
Türü: Araştırma
Tanım: Bir user bu programda hangi featuresları kullanabilir (kullanıcı adı değiştirme, profil düzenle vs.) araştırılması
Ortam: -
Beklenen Çıktı: Kullanıcın kullanabileceği tüm özelliklerin listesi

**Comment by Eralpozcan** [comment]
-Drive'a Rapor eklendi.
