### ISSUE TITLE
Geliştir: Google Reklam Boyutunun kod Olarak Eklenmesi

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/Icon-Projesi#47]
Türü: Kodlama
Tanım: Icon projesine eklenecek olan Google Ads ın programda tasarım boyutunun ve kodunun repoya eklenmesi
Ortam: Css, bootstrap, Figma, Diğerleri
Beklenen Çıktı: Tasarım kodu

**Comment by sinanaksu** [comment]
Google Ads görsel, yazı ve feed türlerinde farklı ve sınırı olmayan dinamik reklam boyutları içeriyor. Ancak Google Ads reklam kodları uygulama içerisinde çalışmıyor. Yapılabilse dahi politikalara aykırı olduğu yazıyor ve Ads hesabının süresiz kapatılması söz konusu oluyor. Uygulama içine bir kaç kod alıp koydum ancak CORS nedeniyle google reklam js kodlarını vermiyor. Bir domain altında boş bir sayfaya sadece reklam kodunu koyarak bu adresi uygulama içinde iframe olarak açma fikrini düşündüm. Ancak boş bir sayfada gösterim ve tıklama alan reklamların hesaplarının da askıya alındığı söyleniyor.

Google Reklamlarının desktop uygulama içerisinde kullanımı bu nedenlerle mümkün görünmüyor.
