### ISSUE TITLE
Geliştir: Harketli Icon Denemesi Örneği

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/Icon-Projesi#49]
Türü: Kodlama
Tanım: Bir dosyada hareketli icon kullanılması örneği, .gif gibi farklı formattan gelen görüntünün icon olarak kullanılması
Ortam: Diğer
Beklenen Çıktı: Repoda ayrı bir branch de örnek

**Comment by sinanaksu** [comment]
Windows 10 için .ico ve .icns uzantılarında hareketli bir görünüm yakalayamadım. Bir kaynaklarda .gif'leri hareketli .apng uzantısına çevirerek bu .apng dosyasının icon olarak klasöre tanımlanabildiği söylenmiş. Bendeki Windows 10 - Build 21H2'de .apng dosyaları işe yaramıyor.

**Comment by serdariset** [comment]
Windows 11'de animated icon yapılamıyor. Bazı forumlarda nasıl yapılır sorularına verilen cevaplar kesinlikle yapılmaması yönünde.
