### ISSUE TITLE
Araştırma: Kominiteye Bağış Ekleme

### ISSUE THREAD

**Issue by FeyzaBiber** [acik-kaynak/Icon-Projesi#54]
Türü: Araştırma veya Kodlama
Tanım: Kullanıcıların projemize destek verebilmeleri için olası featurelar eklenmesi (Buy me Coffee gibi)
Ortam: Diğerleri
Beklenen Çıktı: Repo Farklı bir Feature Branchi

**Comment by Eralpozcan** [comment]
- Added Google Drive
